### ISSUE TITLE
Toolchain installation in fedora.

### ISSUE THREAD

**Issue by Azzzrail** [FPGAwars/toolchain-iverilog#6]
The first error received in the installation script. I replaced "apt-get" to "dnf'.
Second error - No match for argument: build-essential
I tried to install libraries separately, but seems like I failed. Because error "checking whether the C compiler works... no" still remains.
Is there any way to install the toolchain in Fedora (31)?
Thank in advance.

**Comment by Obijuan** [comment]
This package is no longer used and will be archived. Use the tool-oss-cad-suite apio package instead. Thanks
